In [122]:
import pandas as pd
import numpy as np

### Processing on the Monthly GoT data to remove false positives and do date processing

In [123]:
#Read in month of gameofthrones data
GoT_df = pd.read_csv('C:\\data files\\June2016 GOT.csv')

In [124]:
GoT_df.head()

,poster,recipient,relationship,tweet date,tweet id,tweet,hashtags,retweet status
0,M04th,Cutevl,reply,Wed Jun 01 06:32:54 +0000 2016,737894675277852674,@Cutevl انا اصداري اقدم شيء وعادي اخذ سيلفي ما...,[],False
1,aRnecutska,chris_voloshina,mentions,Wed Jun 01 06:34:15 +0000 2016,737895014991302656,RT @chris_voloshina: @aRnecutska моё мнение: к...,[],True
2,aRnecutska,aRnecutska,mentions,Wed Jun 01 06:34:15 +0000 2016,737895014991302656,RT @chris_voloshina: @aRnecutska моё мнение: к...,[],True
3,Macready1306,Macready1306,tweet,Wed Jun 01 06:35:56 +0000 2016,737895438624423937,I've never watched #GameOfThrones so I'd love ...,['GameOfThrones'],False
4,wahanapenulis,wahanapenulis,tweet,Wed Jun 01 06:38:50 +0000 2016,737896168445870080,I'm Tyrion. Discover which #GameOfThrones char...,['GameOfThrones'],False

In [125]:
#Drop all where hashtag != gameofthrones

GoT_df['hashtags'] = GoT_df['hashtags'].str.lower()
GoT_df = GoT_df[GoT_df['hashtags'].str.contains('gameofthrones')]

In [126]:
GoT_df.head(12)

,poster,recipient,relationship,tweet date,tweet id,tweet,hashtags,retweet status
3,Macready1306,Macready1306,tweet,Wed Jun 01 06:35:56 +0000 2016,737895438624423937,I've never watched #GameOfThrones so I'd love ...,['gameofthrones'],False
4,wahanapenulis,wahanapenulis,tweet,Wed Jun 01 06:38:50 +0000 2016,737896168445870080,I'm Tyrion. Discover which #GameOfThrones char...,['gameofthrones'],False
6,scopece_marco,EmiliaClarkeNet,mentions,Wed Jun 01 06:44:16 +0000 2016,737897535788961792,RT @EmiliaClarkeNet: (Video) Emilia Clarke on ...,['gameofthrones'],True
7,scopece_marco,emiliaclarke,mentions,Wed Jun 01 06:44:16 +0000 2016,737897535788961792,RT @EmiliaClarkeNet: (Video) Emilia Clarke on ...,['gameofthrones'],True
8,Yayahemo,GoT_Tyrion,mentions,Wed Jun 01 06:46:08 +0000 2016,737898005542674432,RT @GoT_Tyrion: Who would do this?? #GameofThr...,['gameofthrones'],True
9,HodorRewards,jonsnowyy,mentions,Wed Jun 01 06:49:03 +0000 2016,737898739558404096,RT @jonsnowyy: Well. I'm ready for GOT this we...,"['gameofthrones', 'got', 'jonsnow', 'youknowno...",True
10,ChuckForBlair,Daenerys,mentions,Wed Jun 01 06:49:44 +0000 2016,737898911529066499,RT @Daenerys: Khal Drogo will never be replace...,['gameofthrones'],True
12,6516460c32f4431,FallonTonight,mentions,Wed Jun 01 07:04:47 +0000 2016,737902698985586688,RT @FallonTonight: Kit Harington was pretty te...,['gameofthrones'],True
13,AK_____47,Thrones_Memes,mentions,Wed Jun 01 07:06:49 +0000 2016,737903210665512960,RT @Thrones_Memes: Girl Code #GameOfThrones ht...,['gameofthrones'],True
14,smithstock24,Crackmacs,mentions,Wed Jun 01 07:15:15 +0000 2016,737905333004345344,RT @Crackmacs: Coolest. Gift. Ever. #hodor #ga...,"['hodor', 'gameofthrones']",True
15,smithstock24,jaaxed,mentions,Wed Jun 01 07:15:15 +0000 2016,737905333004345344,RT @Crackmacs: Coolest. Gift. Ever. #hodor #ga...,"['hodor', 'gameofthrones']",True
16,shahryar92,shahryar92,tweet,Wed Jun 01 07:15:43 +0000 2016,737905450419650560,"I can't even... Forget #JonSnow, #MumtazQadri ...","['jonsnow', 'mumtazqadri', 'gameofthrones']",False

In [127]:
GoT_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 47132 entries, 3 to 59268
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   poster          47132 non-null  object
 1   recipient       47131 non-null  object
 2   relationship    47132 non-null  object
 3   tweet date      47132 non-null  object
 4   tweet id        47132 non-null  int64
 5   tweet           47132 non-null  object
 6   hashtags        47132 non-null  object
 7   retweet status  47132 non-null  bool
dtypes: bool(1), int64(1), object(6)
memory usage: 2.9+ MB

In [128]:
#Convert Year column to a datetime objest
GoT_df['tweet date'] = pd.to_datetime(GoT_df['tweet date'])

In [129]:
GoT_df.head(10)

,poster,recipient,relationship,tweet date,tweet id,tweet,hashtags,retweet status
3,Macready1306,Macready1306,tweet,2016-06-01 06:35:56+00:00,737895438624423937,I've never watched #GameOfThrones so I'd love ...,['gameofthrones'],False
4,wahanapenulis,wahanapenulis,tweet,2016-06-01 06:38:50+00:00,737896168445870080,I'm Tyrion. Discover which #GameOfThrones char...,['gameofthrones'],False
6,scopece_marco,EmiliaClarkeNet,mentions,2016-06-01 06:44:16+00:00,737897535788961792,RT @EmiliaClarkeNet: (Video) Emilia Clarke on ...,['gameofthrones'],True
7,scopece_marco,emiliaclarke,mentions,2016-06-01 06:44:16+00:00,737897535788961792,RT @EmiliaClarkeNet: (Video) Emilia Clarke on ...,['gameofthrones'],True
8,Yayahemo,GoT_Tyrion,mentions,2016-06-01 06:46:08+00:00,737898005542674432,RT @GoT_Tyrion: Who would do this?? #GameofThr...,['gameofthrones'],True
9,HodorRewards,jonsnowyy,mentions,2016-06-01 06:49:03+00:00,737898739558404096,RT @jonsnowyy: Well. I'm ready for GOT this we...,"['gameofthrones', 'got', 'jonsnow', 'youknowno...",True
10,ChuckForBlair,Daenerys,mentions,2016-06-01 06:49:44+00:00,737898911529066499,RT @Daenerys: Khal Drogo will never be replace...,['gameofthrones'],True
12,6516460c32f4431,FallonTonight,mentions,2016-06-01 07:04:47+00:00,737902698985586688,RT @FallonTonight: Kit Harington was pretty te...,['gameofthrones'],True
13,AK_____47,Thrones_Memes,mentions,2016-06-01 07:06:49+00:00,737903210665512960,RT @Thrones_Memes: Girl Code #GameOfThrones ht...,['gameofthrones'],True
14,smithstock24,Crackmacs,mentions,2016-06-01 07:15:15+00:00,737905333004345344,RT @Crackmacs: Coolest. Gift. Ever. #hodor #ga...,"['hodor', 'gameofthrones']",True

In [130]:
GoT_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 47132 entries, 3 to 59268
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   poster          47132 non-null  object
 1   recipient       47131 non-null  object
 2   relationship    47132 non-null  object
 3   tweet date      47132 non-null  datetime64[ns, UTC]
 4   tweet id        47132 non-null  int64
 5   tweet           47132 non-null  object
 6   hashtags        47132 non-null  object
 7   retweet status  47132 non-null  bool
dtypes: bool(1), datetime64[ns, UTC](1), int64(1), object(5)
memory usage: 2.9+ MB

In [131]:
#Add a month, day, week and year value to the dataframe
GoT_df['day'] = GoT_df['tweet date'].dt.day
GoT_df['week'] = GoT_df['tweet date'].dt.week
GoT_df['month'] = GoT_df['tweet date'].dt.month
GoT_df['year'] = GoT_df['tweet date'].dt.year
GoT_df['date'] = GoT_df['tweet date'].dt.date

C:\Users\tonyw\AppData\Local\Temp\ipykernel_3924\3577481597.py:3: FutureWarning: Series.dt.weekofyear and Series.dt.week have been deprecated. Please use Series.dt.isocalendar().week instead.
  GoT_df['week'] = GoT_df['tweet date'].dt.week

In [132]:
GoT_df.head()

,poster,recipient,relationship,tweet date,tweet id,tweet,hashtags,retweet status,day,week,month,year,date
3,Macready1306,Macready1306,tweet,2016-06-01 06:35:56+00:00,737895438624423937,I've never watched #GameOfThrones so I'd love ...,['gameofthrones'],False,1,22,6,2016,2016-06-01
4,wahanapenulis,wahanapenulis,tweet,2016-06-01 06:38:50+00:00,737896168445870080,I'm Tyrion. Discover which #GameOfThrones char...,['gameofthrones'],False,1,22,6,2016,2016-06-01
6,scopece_marco,EmiliaClarkeNet,mentions,2016-06-01 06:44:16+00:00,737897535788961792,RT @EmiliaClarkeNet: (Video) Emilia Clarke on ...,['gameofthrones'],True,1,22,6,2016,2016-06-01
7,scopece_marco,emiliaclarke,mentions,2016-06-01 06:44:16+00:00,737897535788961792,RT @EmiliaClarkeNet: (Video) Emilia Clarke on ...,['gameofthrones'],True,1,22,6,2016,2016-06-01
8,Yayahemo,GoT_Tyrion,mentions,2016-06-01 06:46:08+00:00,737898005542674432,RT @GoT_Tyrion: Who would do this?? #GameofThr...,['gameofthrones'],True,1,22,6,2016,2016-06-01

In [133]:
#Drop unwanted columns
#Dropping columns tweet id and tweet date as they are no longer needed
GoT_df.drop(['tweet date','tweet id'], axis=1,inplace=True)

In [134]:
GoT_df.head()

,poster,recipient,relationship,tweet,hashtags,retweet status,day,week,month,year,date
3,Macready1306,Macready1306,tweet,I've never watched #GameOfThrones so I'd love ...,['gameofthrones'],False,1,22,6,2016,2016-06-01
4,wahanapenulis,wahanapenulis,tweet,I'm Tyrion. Discover which #GameOfThrones char...,['gameofthrones'],False,1,22,6,2016,2016-06-01
6,scopece_marco,EmiliaClarkeNet,mentions,RT @EmiliaClarkeNet: (Video) Emilia Clarke on ...,['gameofthrones'],True,1,22,6,2016,2016-06-01
7,scopece_marco,emiliaclarke,mentions,RT @EmiliaClarkeNet: (Video) Emilia Clarke on ...,['gameofthrones'],True,1,22,6,2016,2016-06-01
8,Yayahemo,GoT_Tyrion,mentions,RT @GoT_Tyrion: Who would do this?? #GameofThr...,['gameofthrones'],True,1,22,6,2016,2016-06-01

In [135]:
#Save file for import to nosql
GoT_df.to_csv('C:\\data files\\June2016 GOT Clean.csv')